<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Cases Report</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 20px;
        }

        th,
        td {
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2
        }
    </style>

</head>

<body>
    <div style="margin-bottom:25px;"><strong>Report generated By: {{ Auth::user()->name }}</strong></div>
    <div style="margin-bottom:25px;"><strong>Report generated at: {{ Carbon\Carbon::now() }}</strong></div>
    <table style="border-collapse: collapse;">
        <thead>
            <tr>
                <th style="border-bottom:2pt solid black;">
                    <strong>No</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Name</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Phone</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Disease</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Date</strong>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach ($results as $result)
                <tr>
                    <td style="border-bottom:1pt solid black;">
                        {{ $result->id }}
                    </td>
                    <td style="border-bottom:1pt solid black;">
                        {{ $result->name }}
                    </td>
                    <td style="border-bottom:1pt solid black;">
                        {{ $result->phone }}
                    </td>
                    <td style="border-bottom:1pt solid black;">
                        {{ $result->disease->name }}
                    </td>
                    <td style="border-bottom:1pt solid black;">
                        {{ $result->created_at }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html>
